name: Hass Backup
version: 1.0.1
slug: hass_backup
description: Automatically create backups and store them off-site
url: https://github.com/IDmedia/hass-addons/tree/master/hass-backup
startup: once
boot: manual
hassio_api: true
hassio_role: backup
init: false
map:
  - backup:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  host: ''
  username: ''
  password: ''
schema:
  host: str
  username: str
  password: str
