version: '3'

services:
  hass-backup:
    container_name: hass-backup
    restart: always
    build: ./
    ports:
      - '8070:80'
    environment:
      - LIMIT_BACKUPS=7
      - TZ=Europe/Oslo
    volumes:
      - '/volume2/docker/hass-backup/app:/app'
    image: hass-backup:latest